
ALTER TABLE T_SERVICEPROVIDER DROP PRIMARY KEY CASCADE;
DROP TABLE T_SERVICEPROVIDER CASCADE CONSTRAINTS;

CREATE TABLE T_SERVICEPROVIDER
(
  SERVICEPROVIDER_KEY    INTEGER                NOT NULL,
  SERVICEPROVIDER_NAME   VARCHAR2(128 BYTE)     NOT NULL,
  CISS_APPLICATION_USER  VARCHAR2(128 BYTE)     NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_T_SERVICEPROVIDER ON T_SERVICEPROVIDER
(SERVICEPROVIDER_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX U_SERVICEPROVIDER ON T_SERVICEPROVIDER
(CISS_APPLICATION_USER, SERVICEPROVIDER_NAME)
LOGGING
NOPARALLEL;


DROP TABLE T_IDENTITY_TO_SP CASCADE CONSTRAINTS;

CREATE TABLE T_IDENTITY_TO_SP
(
  IDENTITY_KEY         INTEGER                  NOT NULL,
  SERVICEPROVIDER_KEY  INTEGER                  NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE T_SERVICEPROVIDER ADD (
  CONSTRAINT PK_T_SERVICEPROVIDER PRIMARY KEY (SERVICEPROVIDER_KEY),
  CONSTRAINT U_SERVICEPROVIDER UNIQUE (CISS_APPLICATION_USER, SERVICEPROVIDER_NAME));

ALTER TABLE T_IDENTITY_TO_SP ADD (
  CONSTRAINT FK_IDENTITY_TO_SP FOREIGN KEY (IDENTITY_KEY) 
    REFERENCES T_IDENTITY (IDENTITY_KEY),
  CONSTRAINT FK2_IDENTITY_TO_SP FOREIGN KEY (SERVICEPROVIDER_KEY) 
    REFERENCES T_SERVICEPROVIDER (SERVICEPROVIDER_KEY));



